spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8888



  spring:
    cloud:
      gateway:
        globalcors:
          cors-configurations:
            '[/**]':
              allowed-origins: http://localhost:4200
              allowed-methods: GET, POST, PUT, DELETE, OPTIONS
              allowed-headers: Content-Type, Authorization
              allow-credentials: true








